# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azhubreader < Formula
  desc "Extract Azure Event Hub messages into JSON files"
  homepage "https://github.com/obay/azhubreader"
  version "0.1.5"
  license "MIT"

  on_macos do
    on_intel do
      url "http://github.com/obay/azhubreader/releases/download/v0.1.5/azhubreader_Darwin_x86_64.tar.gz"
      sha256 "6d9beaafec848e754ac47f41dc761ccbfc35ca2f6e44bac48c20138790aa1929"

      def install
        bin.install "azhubreader"
      end
    end
    on_arm do
      url "http://github.com/obay/azhubreader/releases/download/v0.1.5/azhubreader_Darwin_arm64.tar.gz"
      sha256 "94c2eb949ef5ffd32e93a6b2237222a669c71eb2c6b43b21b8784583fa8dd687"

      def install
        bin.install "azhubreader"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/obay/azhubreader/releases/download/v0.1.5/azhubreader_Linux_x86_64.tar.gz"
        sha256 "f1b2158f414b6e4ec3b2a04b08a1938f0fdcaa742b462f070f0ef16f54205d17"

        def install
          bin.install "azhubreader"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/obay/azhubreader/releases/download/v0.1.5/azhubreader_Linux_arm64.tar.gz"
        sha256 "7c88a8777a65113b2f864f01c2e0e641109ebe0f09933287a86ccf69735b8234"

        def install
          bin.install "azhubreader"
        end
      end
    end
  end
end
