# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azhubreader < Formula
  desc "Extract Azure Event Hub messages into JSON files"
  homepage "https://github.com/obay/azhubreader"
  version "0.1.8"
  license "MIT"

  on_macos do
    on_intel do
      url "http://github.com/obay/azhubreader/releases/download/v0.1.8/azhubreader_Darwin_x86_64.tar.gz"
      sha256 "7ab797957f3238f912a3054a6cbcc0a0ab41df2a34aaa38dee951dac93a881a4"

      def install
        bin.install "azhubreader"
      end
    end
    on_arm do
      url "http://github.com/obay/azhubreader/releases/download/v0.1.8/azhubreader_Darwin_arm64.tar.gz"
      sha256 "9e287bc194fcd826e713851efcf2545bb84ce4982ba918562d3e7fe9af838670"

      def install
        bin.install "azhubreader"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/obay/azhubreader/releases/download/v0.1.8/azhubreader_Linux_x86_64.tar.gz"
        sha256 "386371cafb18e6d077e9e67a75e3dbce55330819892d99d95f34f851c501760c"

        def install
          bin.install "azhubreader"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/obay/azhubreader/releases/download/v0.1.8/azhubreader_Linux_arm64.tar.gz"
        sha256 "b7c541b11fe0142271877dea8162e291454793096c25099b4bbfa6acd166ed0b"

        def install
          bin.install "azhubreader"
        end
      end
    end
  end
end
