# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hevycli < Formula
  desc "CLI for the Hevy fitness tracking platform"
  homepage "https://github.com/obay/hevycli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obay/hevycli/releases/download/v0.1.0/hevycli_0.1.0_darwin_amd64.tar.gz"
      sha256 "c2f5aa29a46c39a721768ccb27ff8d6288e0232c57620df7d0ad086a665a3774"

      def install
        bin.install "hevycli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obay/hevycli/releases/download/v0.1.0/hevycli_0.1.0_darwin_arm64.tar.gz"
      sha256 "475b99f9133d97adbf28f1997deaefde783bfe5f90f841b059f6b2330c82ca40"

      def install
        bin.install "hevycli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/hevycli/releases/download/v0.1.0/hevycli_0.1.0_linux_amd64.tar.gz"
      sha256 "a2e4d96f16c7db987d0d5ca90b12d448bc424c2fe65eed0895e41a4e49cef348"
      def install
        bin.install "hevycli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/hevycli/releases/download/v0.1.0/hevycli_0.1.0_linux_arm64.tar.gz"
      sha256 "516632640707ecdc4c37db7b8c85371cbfd82e9c1a3c971056030bb83e28ddbd"
      def install
        bin.install "hevycli"
      end
    end
  end

  test do
    system "#{bin}/hevycli", "--version"
  end
end
