# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obcmd < Formula
  desc "Operator CLI for the obcmd remote-exec relay"
  homepage "https://github.com/obay/obcmd"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obay/obcmd/releases/download/v0.1.1/obcmd_0.1.1_darwin_amd64.tar.gz"
      sha256 "4dd48aba59a2a99c32413ba4e48ed28974f4aae52503df50e5b670df164dcea1"

      define_method(:install) do
        bin.install "obcmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obay/obcmd/releases/download/v0.1.1/obcmd_0.1.1_darwin_arm64.tar.gz"
      sha256 "542ff84e74852f52aab8bbdba829ef2338738b65fadce229165b001655019d3f"

      define_method(:install) do
        bin.install "obcmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/obcmd/releases/download/v0.1.1/obcmd_0.1.1_linux_amd64.tar.gz"
      sha256 "b48dde7a97b04822b7dec449bdd3cd6b119e223290552111219df645dd2e9c5e"
      define_method(:install) do
        bin.install "obcmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/obcmd/releases/download/v0.1.1/obcmd_0.1.1_linux_arm64.tar.gz"
      sha256 "44bebc8795574643fa506a9e4f46fb447704d3b6cd15d980de3ee5901ee0d60d"
      define_method(:install) do
        bin.install "obcmd"
      end
    end
  end

  test do
    system "#{bin}/obcmd", "version"
  end
end
