# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obcmdd < Formula
  desc "HTTPS relay for the obcmd remote-exec system"
  homepage "https://github.com/obay/obcmd"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obay/obcmd/releases/download/v0.1.1/obcmdd_0.1.1_darwin_amd64.tar.gz"
      sha256 "6ad794c479d6ecc7ec4dbdd23d1077390b6fc48519c5d3c649c7b96e788d5711"

      define_method(:install) do
        bin.install "obcmdd"
        (etc/"obcmd").mkpath
        pkgshare.install "config.example.obcmdd.toml"
        pkgshare.install "deploy/obcmdd.service" if File.exist?("deploy/obcmdd.service")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obay/obcmd/releases/download/v0.1.1/obcmdd_0.1.1_darwin_arm64.tar.gz"
      sha256 "949b95b746519c09d4974abeecff015bb640f73996de50e7158614df046c0edc"

      define_method(:install) do
        bin.install "obcmdd"
        (etc/"obcmd").mkpath
        pkgshare.install "config.example.obcmdd.toml"
        pkgshare.install "deploy/obcmdd.service" if File.exist?("deploy/obcmdd.service")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/obcmd/releases/download/v0.1.1/obcmdd_0.1.1_linux_amd64.tar.gz"
      sha256 "d5e25e77ebdf6418673a4bacb162dd399096db3260acaab915811d35587e3a5d"
      define_method(:install) do
        bin.install "obcmdd"
        (etc/"obcmd").mkpath
        pkgshare.install "config.example.obcmdd.toml"
        pkgshare.install "deploy/obcmdd.service" if File.exist?("deploy/obcmdd.service")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/obcmd/releases/download/v0.1.1/obcmdd_0.1.1_linux_arm64.tar.gz"
      sha256 "11be635be257adee74520af2e2b28fd570881b58857e74a27f63d2c3c9d48a92"
      define_method(:install) do
        bin.install "obcmdd"
        (etc/"obcmd").mkpath
        pkgshare.install "config.example.obcmdd.toml"
        pkgshare.install "deploy/obcmdd.service" if File.exist?("deploy/obcmdd.service")
      end
    end
  end

  def caveats
    <<~EOS
      Config example: #{HOMEBREW_PREFIX}/share/obcmdd/config.example.obcmdd.toml
      Copy to #{HOMEBREW_PREFIX}/etc/obcmd/obcmdd.toml and edit before starting.
    EOS
  end

  service do
    run [opt_bin/"obcmdd", "serve", "--config", etc/"obcmd/obcmdd.toml"]
    keep_alive true
    log_path var/"log/obcmdd.log"
    error_log_path var/"log/obcmdd.err.log"
  end

  test do
    system "#{bin}/obcmdd", "version"
  end
end
