# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obcmdd < Formula
  desc "HTTPS relay for the obcmd remote-exec system"
  homepage "https://github.com/obay/obcmd"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obay/obcmd/releases/download/v0.1.2/obcmdd_0.1.2_darwin_amd64.tar.gz"
      sha256 "6d28afbb1cf40413f6c05f66cd87636b871c95b0c1290c5505486b3e2e0119ba"

      define_method(:install) do
        bin.install "obcmdd"
        (etc/"obcmd").mkpath
        pkgshare.install "config.example.obcmdd.toml"
        pkgshare.install "deploy/obcmdd.service" if File.exist?("deploy/obcmdd.service")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obay/obcmd/releases/download/v0.1.2/obcmdd_0.1.2_darwin_arm64.tar.gz"
      sha256 "e1dac3571d7ae72b725c05ef17f8dd01279504e1d5a40d94bb0028d84af37030"

      define_method(:install) do
        bin.install "obcmdd"
        (etc/"obcmd").mkpath
        pkgshare.install "config.example.obcmdd.toml"
        pkgshare.install "deploy/obcmdd.service" if File.exist?("deploy/obcmdd.service")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/obcmd/releases/download/v0.1.2/obcmdd_0.1.2_linux_amd64.tar.gz"
      sha256 "834900c65c7dadbbbe1ab20e6e9d37054b45478fb117e0e9f0343f7fe19e7854"
      define_method(:install) do
        bin.install "obcmdd"
        (etc/"obcmd").mkpath
        pkgshare.install "config.example.obcmdd.toml"
        pkgshare.install "deploy/obcmdd.service" if File.exist?("deploy/obcmdd.service")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/obcmd/releases/download/v0.1.2/obcmdd_0.1.2_linux_arm64.tar.gz"
      sha256 "da167439baefc2125b02f9e4175f94fd3ac9a734fd110b7449f92cbd844981f2"
      define_method(:install) do
        bin.install "obcmdd"
        (etc/"obcmd").mkpath
        pkgshare.install "config.example.obcmdd.toml"
        pkgshare.install "deploy/obcmdd.service" if File.exist?("deploy/obcmdd.service")
      end
    end
  end

  def caveats
    <<~EOS
      Config example: #{HOMEBREW_PREFIX}/share/obcmdd/config.example.obcmdd.toml
      Copy to #{HOMEBREW_PREFIX}/etc/obcmd/obcmdd.toml and edit before starting.
    EOS
  end

  service do
    run [opt_bin/"obcmdd", "serve", "--config", etc/"obcmd/obcmdd.toml"]
    keep_alive true
    log_path var/"log/obcmdd.log"
    error_log_path var/"log/obcmdd.err.log"
  end

  test do
    system "#{bin}/obcmdd", "version"
  end
end
