# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obcmd < Formula
  desc "Operator CLI for the obcmd remote-exec relay"
  homepage "https://github.com/obay/obcmd"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obay/obcmd/releases/download/v0.1.0/obcmd_0.1.0_darwin_amd64.tar.gz"
      sha256 "5f8acce6a5678e3c89b6b2242e7f6e8bf41e22a798bda31e126c807353b05203"

      define_method(:install) do
        bin.install "obcmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obay/obcmd/releases/download/v0.1.0/obcmd_0.1.0_darwin_arm64.tar.gz"
      sha256 "b0578c31c7f2b13f46bac76a2ebed7c2fd57fda81feb4ef168b19ae5c323c165"

      define_method(:install) do
        bin.install "obcmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/obcmd/releases/download/v0.1.0/obcmd_0.1.0_linux_amd64.tar.gz"
      sha256 "a0f6efbec4cceacd74f1b1f191f0b4a34b3e232d7009e68b01ab4040a4b8aa8e"
      define_method(:install) do
        bin.install "obcmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/obcmd/releases/download/v0.1.0/obcmd_0.1.0_linux_arm64.tar.gz"
      sha256 "8eb0fc3cd62f5409af28d60014d1719fb3f87ecb010572bd238df36610e88e41"
      define_method(:install) do
        bin.install "obcmd"
      end
    end
  end

  test do
    system "#{bin}/obcmd", "version"
  end
end
