# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rcmdd < Formula
  desc "HTTPS relay for the rcmd remote-exec system (Linux only)"
  homepage "https://github.com/obay/rcmd"
  version "0.2.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/obay/rcmd/releases/download/v0.2.0/rcmdd_0.2.0_linux_amd64.tar.gz"
    sha256 "0b53b82c54d264219146324aec4d9b35fb31a9b81758baf9900fadb0cdd91f54"
    define_method(:install) do
      bin.install "rcmdd"
      pkgshare.install "deploy/rcmdd.service" if File.exist?("deploy/rcmdd.service")
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/obay/rcmd/releases/download/v0.2.0/rcmdd_0.2.0_linux_arm64.tar.gz"
    sha256 "e49a968822040583673c7835a31bd81877068bdcd5545b91d717c1430934ae3c"
    define_method(:install) do
      bin.install "rcmdd"
      pkgshare.install "deploy/rcmdd.service" if File.exist?("deploy/rcmdd.service")
    end
  end

  def caveats
    <<~EOS
      Run once before starting the service:
        sudo rcmdd init --domain relay.example.com
      Then:
        brew services start rcmdd
    EOS
  end

  service do
    run [opt_bin/"rcmdd", "serve"]
    keep_alive true
    log_path var/"log/rcmdd.log"
    error_log_path var/"log/rcmdd.err.log"
  end

  test do
    system "#{bin}/rcmdd", "version"
  end
end
