# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rcmd < Formula
  desc "Operator CLI for the rcmd remote-exec relay"
  homepage "https://github.com/obay/rcmd"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obay/rcmd/releases/download/v0.2.0/rcmd_0.2.0_darwin_amd64.tar.gz"
      sha256 "4b53743d67aecae5ec03f29612c8614a4aa65350f9f1180fa1b3ac8d94e8b0c1"

      define_method(:install) do
        bin.install "rcmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obay/rcmd/releases/download/v0.2.0/rcmd_0.2.0_darwin_arm64.tar.gz"
      sha256 "979eba8ef050d7f6598d6c9790893a7a72a5a39fc8b09ff32fa75e4a121eac07"

      define_method(:install) do
        bin.install "rcmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/rcmd/releases/download/v0.2.0/rcmd_0.2.0_linux_amd64.tar.gz"
      sha256 "870820066b45ea493996d80be18b7d75bca84b798092b4338b898613485ac267"
      define_method(:install) do
        bin.install "rcmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/rcmd/releases/download/v0.2.0/rcmd_0.2.0_linux_arm64.tar.gz"
      sha256 "1def60135151b031091dbb547e78eff035c70433744bbb50d41448d9af4a6c2e"
      define_method(:install) do
        bin.install "rcmd"
      end
    end
  end

  test do
    system "#{bin}/rcmd", "version"
  end
end
