# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rcmt < Formula
  desc "A rudimentary configuration management tool for Slack Challenge."
  homepage "https://Github.com/obay/rcmt"
  version "0.10.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "http://github.com/obay/rcmt/releases/download/v0.10.0/rcmt_0.10.0_Darwin_x86_64.tar.gz"
    sha256 "538d11bfb8453f41e370394681c5d0f79da6d15a404008634225633933bff37a"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "http://github.com/obay/rcmt/releases/download/v0.10.0/rcmt_0.10.0_Darwin_arm64.tar.gz"
    sha256 "2501873a3903ac39d94f7db820e3ac72a1e87543ce4b6f78eed90fff4c75b2f4"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "http://github.com/obay/rcmt/releases/download/v0.10.0/rcmt_0.10.0_Linux_x86_64.tar.gz"
    sha256 "aeec366020d713ee2ac073f68c51f91feef8b6c1ec02f7ce34f8bc003f5c4eb7"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "http://github.com/obay/rcmt/releases/download/v0.10.0/rcmt_0.10.0_Linux_arm64.tar.gz"
    sha256 "48744982ab44550fd9c7424a7bf0b81697b739756c0a4e8343dd3e2411c0b70d"
  end

  depends_on "go" => :build

  def install
    bin.install "rcmt"
  end

  test do
    assert shell_output("#{bin}/rcmt version")
  end
end
