# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfctl < Formula
  desc "A tool to rename Terraform files accodrind to the resource type and name."
  homepage "https://github.com/obay/tfctl"
  version "1.0.7"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/obay/tfctl/releases/download/v1.0.7/tfctl_1.0.7_darwin_arm64.tar.gz"
      sha256 "ce791085a91864739d0ba229d703c7755d2f297efa2907ed0201df109f354eb6"

      def install
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/obay/tfctl/releases/download/v1.0.7/tfctl_1.0.7_darwin_amd64.tar.gz"
      sha256 "860d9606df08079706a779c3fc26f3bf3698749ea373123a5adb18124ebaff28"

      def install
        bin.install "tfctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/obay/tfctl/releases/download/v1.0.7/tfctl_1.0.7_linux_arm64.tar.gz"
      sha256 "698b88c35de879ab9ddb36d230f74ced260f129eac577fc10b06ab64c97d996a"

      def install
        bin.install "tfctl"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/obay/tfctl/releases/download/v1.0.7/tfctl_1.0.7_linux_amd64.tar.gz"
      sha256 "e7648cceaac03676bd5c054451ea38a4005254fafe2a301bcab5531325fd893c"

      def install
        bin.install "tfctl"
      end
    end
  end

  test do
    assert shell_output("#{bin}/tfctl version")
  end
end
