# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfren < Formula
  desc "A tool to rename Terraform files accodrind to the resource type and name."
  homepage "https://github.com/obay/tfren"
  version "0.4.3"

  depends_on "go" => :build

  on_macos do
    on_intel do
      url "http://github.com/obay/tfren/releases/download/v0.4.3/tfren_Darwin_x86_64.tar.gz"
      sha256 "8fdd4aa2593c630c0ad930af57eea22475abf56f2d7351f706186f91ead08ebb"

      def install
        bin.install "tfren"
      end
    end
    on_arm do
      url "http://github.com/obay/tfren/releases/download/v0.4.3/tfren_Darwin_arm64.tar.gz"
      sha256 "c7e9debc661e94e5bf6cf12a6d22b3a32e7caf7ddea62221fdfc1a951b534435"

      def install
        bin.install "tfren"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/obay/tfren/releases/download/v0.4.3/tfren_Linux_x86_64.tar.gz"
        sha256 "41db7d26ca4fe51fb35389973f2312fe29188fff5779ed4924824e6fbc71306a"

        def install
          bin.install "tfren"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/obay/tfren/releases/download/v0.4.3/tfren_Linux_arm64.tar.gz"
        sha256 "a5777cd0dc085dc9d9d00f11b0b9c41734d408d0f0d05f5f15429f3f09b2a780"

        def install
          bin.install "tfren"
        end
      end
    end
  end

  test do
    assert shell_output("#{bin}/tfren version")
  end
end
