# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfren < Formula
  desc "A tool to rename Terraform files accodrind to the resource type and name."
  homepage "https://github.com/obay/tfren"
  version "0.1.4"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/obay/tfren/releases/download/v0.1.4/tfren_0.1.4_Darwin_arm64.tar.gz"
      sha256 "8f6bdf090a2446f31e11d227dd40260a67edd84e106fb940bb7fb24aa9bb00c0"

      def install
        bin.install "tfren"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/obay/tfren/releases/download/v0.1.4/tfren_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "1c6a5e04cab3e0c3764deaf2b2ec353a2501c529e51245c41f6c6ba3063f54f5"

      def install
        bin.install "tfren"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/obay/tfren/releases/download/v0.1.4/tfren_0.1.4_Linux_arm64.tar.gz"
      sha256 "51b4baf6ae394fbc84a7b1dd50b1ecd5ec4d27f1a76e91fe4a2a3f2d9e8ae878"

      def install
        bin.install "tfren"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/obay/tfren/releases/download/v0.1.4/tfren_0.1.4_Linux_x86_64.tar.gz"
      sha256 "3cca6c9c24fa52597390a12d1dcc05147c40969129c7572782cb712341af4cb6"

      def install
        bin.install "tfren"
      end
    end
  end

  test do
    assert shell_output("#{bin}/tfren version")
  end
end
