# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfsplit < Formula
  desc "A tool to rename Terraform files accodrind to the resource type and name."
  homepage "https://github.com/obay/tfsplit"
  version "2.0.6"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/obay/tfsplit/releases/download/v2.0.6/tfsplit_2.0.6_darwin_arm64.tar.gz"
      sha256 "388deb12fffe327539099e053e887cb13c20212ae896642e8686f76d46824ab9"

      def install
        bin.install "tfsplit"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/obay/tfsplit/releases/download/v2.0.6/tfsplit_2.0.6_darwin_amd64.tar.gz"
      sha256 "0678f30a1f25304a7b0ccc0198840d092e2f80649b977c400986444fa31f8ceb"

      def install
        bin.install "tfsplit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/obay/tfsplit/releases/download/v2.0.6/tfsplit_2.0.6_linux_arm64.tar.gz"
      sha256 "6c1d0d692cd04009a0f545c59d97260c9c66834cb498c227c572a3fc4d3fae4a"

      def install
        bin.install "tfsplit"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/obay/tfsplit/releases/download/v2.0.6/tfsplit_2.0.6_linux_amd64.tar.gz"
      sha256 "0f66427a9f12028b74233c3d019c63642749db4df83f528f25353474ee7c94fa"

      def install
        bin.install "tfsplit"
      end
    end
  end

  test do
    assert shell_output("#{bin}/tfsplit version")
  end
end
