# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfsplit < Formula
  desc "A tool to rename Terraform files accodrind to the resource type and name."
  homepage "https://github.com/obay/tfsplit"
  version "0.0.1"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/obay/tfsplit/releases/download/v0.0.1/tfsplit_0.0.1_darwin_amd64.tar.gz"
      sha256 "3c3dace21bb803567956a13534bb59c7ea74988a45dbaa0995b3a8d4f4079526"

      def install
        bin.install "tfsplit"
      end
    end
    if Hardware::CPU.arm?
      url "http://github.com/obay/tfsplit/releases/download/v0.0.1/tfsplit_0.0.1_darwin_arm64.tar.gz"
      sha256 "99ba792b919c12b10be853e16cf1833c1c862b27490d50e7a02b3ad7b89a9c23"

      def install
        bin.install "tfsplit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/obay/tfsplit/releases/download/v0.0.1/tfsplit_0.0.1_linux_arm64.tar.gz"
      sha256 "a32c1de68d8d719a562f33d75a6ce127d2708a523870d9cb214d345b75a3394e"

      def install
        bin.install "tfsplit"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/obay/tfsplit/releases/download/v0.0.1/tfsplit_0.0.1_linux_amd64.tar.gz"
      sha256 "54427f3e8d69e920c6b3136e649116cef365e53fa1cba46edf5bc56aea531e65"

      def install
        bin.install "tfsplit"
      end
    end
  end

  test do
    assert shell_output("#{bin}/tfsplit version")
  end
end
