# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfsplit < Formula
  desc "A tool to rename Terraform files accodrind to the resource type and name."
  homepage "https://github.com/obay/tfsplit"
  version "2.0.7"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.arm?
      url "http://github.com/obay/tfsplit/releases/download/v2.0.7/tfsplit_2.0.7_darwin_arm64.tar.gz"
      sha256 "fd140adba8eb82019c66ceecc7f060f3d0c0fdc00ef8d6432d92b1310140c6a2"

      def install
        bin.install "tfsplit"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/obay/tfsplit/releases/download/v2.0.7/tfsplit_2.0.7_darwin_amd64.tar.gz"
      sha256 "1b91f45d993a1489d3b349cf6295a2badeae32c1a2c9e5b3085edf3499130e5d"

      def install
        bin.install "tfsplit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/obay/tfsplit/releases/download/v2.0.7/tfsplit_2.0.7_linux_arm64.tar.gz"
      sha256 "cb60e58db3a14f8a4541650aea30f4cee4f231f1052b096354082aba36e45b7d"

      def install
        bin.install "tfsplit"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/obay/tfsplit/releases/download/v2.0.7/tfsplit_2.0.7_linux_amd64.tar.gz"
      sha256 "b2082a52016524712a51c26bb43ef02b33d4457da1f96efab7fc13dfc72a8e84"

      def install
        bin.install "tfsplit"
      end
    end
  end

  test do
    assert shell_output("#{bin}/tfsplit version")
  end
end
