# This file was generated by GoReleaser. DO NOT EDIT.
cask "hevycli" do
  name "hevycli"
  desc "CLI for the Hevy fitness tracking platform"
  homepage "https://github.com/obay/hevycli"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hevycli"

  on_macos do
    on_intel do
      url "https://github.com/obay/hevycli/releases/download/v#{version}/hevycli_#{version}_darwin_amd64.tar.gz"
      sha256 "875bc5070c69baad3b1c1bfb3fab26f79fcead6796a42669a2fceb5bfad91180"
    end
    on_arm do
      url "https://github.com/obay/hevycli/releases/download/v#{version}/hevycli_#{version}_darwin_arm64.tar.gz"
      sha256 "6752fef7d4942db4a990a4b829d136bd7b5e263a80c90f3d715291ce7cde87a0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/obay/hevycli/releases/download/v#{version}/hevycli_#{version}_linux_amd64.tar.gz"
      sha256 "1cad5cfa55059b5e98044af256fdc8fb13bdae2918117435e3580a21f0ad6813"
    end
    on_arm do
      url "https://github.com/obay/hevycli/releases/download/v#{version}/hevycli_#{version}_linux_arm64.tar.gz"
      sha256 "5d68eada5d8a5914517702bfae37b493649c96c66a94420ca87984bf33c00a14"
    end
  end

  # No zap stanza required
end
