# This file was generated by GoReleaser. DO NOT EDIT.
cask "hscli" do
  name "hscli"
  desc "A CLI tool for managing HubSpot contacts"
  homepage "https://github.com/obay/hscli"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hscli"

  on_macos do
    on_intel do
      url "https://github.com/obay/hscli/releases/download/v#{version}/hscli_darwin_amd64.tar.gz",
        verified: "github.com/obay/hscli"
      sha256 "0669e40a0b6fed10b9b30e33d91eff0b9037ea808bb2a585669ad6f4c17669f2"
    end
    on_arm do
      url "https://github.com/obay/hscli/releases/download/v#{version}/hscli_darwin_arm64.tar.gz",
        verified: "github.com/obay/hscli"
      sha256 "3e5d738b0f5a953fc49c62c00d11d719c71e0b1dec5bd7eeff3468578572ce3a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/obay/hscli/releases/download/v#{version}/hscli_linux_amd64.tar.gz",
        verified: "github.com/obay/hscli"
      sha256 "e10c11bd427672e919d67d1b9c11df033706e124d238e71b28712649aabc6e7c"
    end
    on_arm do
      url "https://github.com/obay/hscli/releases/download/v#{version}/hscli_linux_arm64.tar.gz",
        verified: "github.com/obay/hscli"
      sha256 "09c61823b681b547b5817545689d9b6906da948490bf5a8fdea090b1bf59b32e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hscli"], sudo: false
    end
  end

  # No zap stanza required
end
