# This file was generated by GoReleaser. DO NOT EDIT.
cask "hscli" do
  name "hscli"
  desc "A CLI tool for managing HubSpot contacts"
  homepage "https://github.com/obay/hscli"
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hscli"

  on_macos do
    on_intel do
      url "https://github.com/obay/hscli/releases/download/v#{version}/hscli_darwin_amd64.tar.gz",
        verified: "github.com/obay/hscli"
      sha256 "f62560bacb2bb7c69b83553c7925957fcd3c1ee94c26a6a6b4b8739aa2e932d3"
    end
    on_arm do
      url "https://github.com/obay/hscli/releases/download/v#{version}/hscli_darwin_arm64.tar.gz",
        verified: "github.com/obay/hscli"
      sha256 "288be554b2677991c18a9ced288563d8425aac168495def0f3494d2644649421"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/obay/hscli/releases/download/v#{version}/hscli_linux_amd64.tar.gz",
        verified: "github.com/obay/hscli"
      sha256 "ac967d4513c60dad96ef833ceeadba4733e42e178fadea0854a36aed287e734e"
    end
    on_arm do
      url "https://github.com/obay/hscli/releases/download/v#{version}/hscli_linux_arm64.tar.gz",
        verified: "github.com/obay/hscli"
      sha256 "6a69a869fbfa1f7a7bfe4e29b4e76932c0795cd750c080739db024631fe1d68b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hscli"], sudo: false
    end
  end

  # No zap stanza required
end
