# This file was generated by GoReleaser. DO NOT EDIT.
cask "hscli" do
  name "hscli"
  desc "A CLI tool for managing HubSpot contacts"
  homepage "https://github.com/obay/hscli"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hscli"

  on_macos do
    on_intel do
      url "https://github.com/obay/hscli/releases/download/v#{version}/hscli_darwin_amd64.tar.gz",
        verified: "github.com/obay/hscli"
      sha256 "2ab4fa5d32f37de3cbd7e69db198219d8c9dd2afa9e844282a3829f639ab9c34"
    end
    on_arm do
      url "https://github.com/obay/hscli/releases/download/v#{version}/hscli_darwin_arm64.tar.gz",
        verified: "github.com/obay/hscli"
      sha256 "138fae129136fa11aeea298a51e29ed7a5f921d0c55192593c9fac9af668e829"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/obay/hscli/releases/download/v#{version}/hscli_linux_amd64.tar.gz",
        verified: "github.com/obay/hscli"
      sha256 "c328bfec04cf293b4be14b7dd75b6c43afbba85399fbfb05b34d906db3ce9693"
    end
    on_arm do
      url "https://github.com/obay/hscli/releases/download/v#{version}/hscli_linux_arm64.tar.gz",
        verified: "github.com/obay/hscli"
      sha256 "f6fa106f89c136350e0f1979aede80e45c50e4bec95d720bca7a1efc03f2311d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hscli"], sudo: false
    end
  end

  # No zap stanza required
end
