# This file was generated by GoReleaser. DO NOT EDIT.
cask "hsctl" do
  name "hsctl"
  desc "A CLI tool for managing HubSpot contacts"
  homepage "https://github.com/obay/hsctl"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hsctl"

  on_macos do
    on_intel do
      url "https://github.com/obay/hsctl/releases/download/v#{version}/hsctl_darwin_amd64.tar.gz",
        verified: "github.com/obay/hsctl"
      sha256 "f30c7da37b8a167ec84107a22e4ccf8ad2602840ddb2575537e7cba2d09bcbb3"
    end
    on_arm do
      url "https://github.com/obay/hsctl/releases/download/v#{version}/hsctl_darwin_arm64.tar.gz",
        verified: "github.com/obay/hsctl"
      sha256 "440fa11ccbd08960508c42f50c1d11d9e5aa2bde583fb3d4b2479d8f12bf3065"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/obay/hsctl/releases/download/v#{version}/hsctl_linux_amd64.tar.gz",
        verified: "github.com/obay/hsctl"
      sha256 "13d5b9d710e52c8633c90c32653aed57905e434ea66056a340bab6e495138750"
    end
    on_arm do
      url "https://github.com/obay/hsctl/releases/download/v#{version}/hsctl_linux_arm64.tar.gz",
        verified: "github.com/obay/hsctl"
      sha256 "5ac631d06a94d172ca4e176dd4997a6ecb48f3905f644d086602d90876661664"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hsctl"], sudo: false
    end
  end

  # No zap stanza required
end
