# This file was generated by GoReleaser. DO NOT EDIT.
cask "hsctl" do
  name "hsctl"
  desc "A CLI tool for managing HubSpot contacts"
  homepage "https://github.com/obay/hsctl"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hsctl"

  on_macos do
    on_intel do
      url "https://github.com/obay/hsctl/releases/download/v#{version}/hsctl_darwin_amd64.tar.gz",
        verified: "github.com/obay/hsctl"
      sha256 "4598c05fbb464c94d42a8307021d628b278d8d0ab59d6816680aeb20cf1d3a49"
    end
    on_arm do
      url "https://github.com/obay/hsctl/releases/download/v#{version}/hsctl_darwin_arm64.tar.gz",
        verified: "github.com/obay/hsctl"
      sha256 "04a379abed55364a7f6202a78c3808a5d3f376b95c252a57789c8ec29206fb7a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/obay/hsctl/releases/download/v#{version}/hsctl_linux_amd64.tar.gz",
        verified: "github.com/obay/hsctl"
      sha256 "96cc7108f7d6618a0cc50ce34022add306ac1273496d00b427949c30074b3c80"
    end
    on_arm do
      url "https://github.com/obay/hsctl/releases/download/v#{version}/hsctl_linux_arm64.tar.gz",
        verified: "github.com/obay/hsctl"
      sha256 "0079dda8e5ca814e0e6a71d6f9f31cf810671fc51796b814866eca6d71ec3ff7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hsctl"], sudo: false
    end
  end

  # No zap stanza required
end
