# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azhubreader < Formula
  desc "Extract Azure Event Hub messages into JSON files"
  homepage "https://github.com/obay/azhubreader"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "http://github.com/obay/azhubreader/releases/download/v0.1.3/azhubreader_Darwin_x86_64.tar.gz"
      sha256 "20ec4b3eed7ed6bac23dd9b8a4d7f57b55943de9bd0bca1a15c3be31f708489f"

      def install
        bin.install "azhubreader"
      end
    end
    on_arm do
      url "http://github.com/obay/azhubreader/releases/download/v0.1.3/azhubreader_Darwin_arm64.tar.gz"
      sha256 "773aa374d9f7a4f057c3c9c656fa6092a7694eb4f6cc4407a400cf2361a52be0"

      def install
        bin.install "azhubreader"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/obay/azhubreader/releases/download/v0.1.3/azhubreader_Linux_x86_64.tar.gz"
        sha256 "9499f4214d5e148daf88acf0f3b637fd3945ea3635fc8ee019046cb4a1b69212"

        def install
          bin.install "azhubreader"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/obay/azhubreader/releases/download/v0.1.3/azhubreader_Linux_arm64.tar.gz"
        sha256 "dc942029d8f1fda4fcc7bed7b5df9828347b527a0970be5ac7f32af6631e0080"

        def install
          bin.install "azhubreader"
        end
      end
    end
  end
end
