# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qbcli < Formula
  desc "Command-line interface for QuickBooks Online"
  homepage "https://github.com/obay/qbcli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obay/qbcli/releases/download/v0.1.0/qbcli_0.1.0_darwin_amd64.tar.gz"
      sha256 "fa7fc24fb42d1104e36bf76385a2395cb2f4bb6e1998d2f9a2c3cf8ef5a98293"

      def install
        bin.install "qbcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obay/qbcli/releases/download/v0.1.0/qbcli_0.1.0_darwin_arm64.tar.gz"
      sha256 "a73d6f3ecd3855ad72e5d432ffe93d1fccc8261415f4d0a2cf2165f1ff05d741"

      def install
        bin.install "qbcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/qbcli/releases/download/v0.1.0/qbcli_0.1.0_linux_amd64.tar.gz"
      sha256 "cfb865ba9512a2630e0fc18b0a9fab33c5c8a5073688a0a8502e8ba59ca71abe"
      def install
        bin.install "qbcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/qbcli/releases/download/v0.1.0/qbcli_0.1.0_linux_arm64.tar.gz"
      sha256 "62b48a9005dbbf084d0b90e0a7aa10a88506016e5b37c76cb12dacac740db480"
      def install
        bin.install "qbcli"
      end
    end
  end

  test do
    system "#{bin}/qbcli", "version"
  end
end
