# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rcmd < Formula
  desc "Operator CLI for the rcmd remote-exec relay"
  homepage "https://github.com/obay/rcmd"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obay/rcmd/releases/download/v0.3.1/rcmd_0.3.1_darwin_amd64.tar.gz"
      sha256 "ed39bc9b4a6cf826c8d479cb404360baa7e9886feceb69555f12508ff9529dd3"

      define_method(:install) do
        bin.install "rcmd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obay/rcmd/releases/download/v0.3.1/rcmd_0.3.1_darwin_arm64.tar.gz"
      sha256 "329072c446f5351244dc95c80289548578a29da9676bd897483f9d1153e41198"

      define_method(:install) do
        bin.install "rcmd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/rcmd/releases/download/v0.3.1/rcmd_0.3.1_linux_amd64.tar.gz"
      sha256 "c5e44947d9f7062b6facf6237553a57a64be2d956762be8646794f4426d11e01"
      define_method(:install) do
        bin.install "rcmd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/rcmd/releases/download/v0.3.1/rcmd_0.3.1_linux_arm64.tar.gz"
      sha256 "463b62e9a01ae3f29cf178171e01afae2682a5d5ee06af5553cf9beb2ded3160"
      define_method(:install) do
        bin.install "rcmd"
      end
    end
  end

  test do
    system "#{bin}/rcmd", "version"
  end
end
