# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rcmdd < Formula
  desc "HTTPS relay for the rcmd remote-exec system (Linux only)"
  homepage "https://github.com/obay/rcmd"
  version "0.2.1"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/obay/rcmd/releases/download/v0.2.1/rcmdd_0.2.1_linux_amd64.tar.gz"
    sha256 "93b82d87bff2e02d143720391a1834c79d93f205255e294a81c1ce4d17885e5b"
    define_method(:install) do
      bin.install "rcmdd"
      pkgshare.install "deploy/rcmdd.service" if File.exist?("deploy/rcmdd.service")
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/obay/rcmd/releases/download/v0.2.1/rcmdd_0.2.1_linux_arm64.tar.gz"
    sha256 "2dbb0cef3054927f5ebadcb7fa435e3cd5a872addac999fa442a3392e2e3641e"
    define_method(:install) do
      bin.install "rcmdd"
      pkgshare.install "deploy/rcmdd.service" if File.exist?("deploy/rcmdd.service")
    end
  end

  def caveats
    <<~EOS
      Run once before starting the service:
        sudo rcmdd init --domain relay.example.com
      Then:
        brew services start rcmdd
    EOS
  end

  service do
    run [opt_bin/"rcmdd", "serve"]
    keep_alive true
    log_path var/"log/rcmdd.log"
    error_log_path var/"log/rcmdd.err.log"
  end

  test do
    system "#{bin}/rcmdd", "version"
  end
end
