# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfren < Formula
  desc "Terraform file organizer - splits and renames files according to OTN naming convention."
  homepage "https://github.com/obay/tfren"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obay/tfren/releases/download/v1.0.3/tfren_Darwin_x86_64.tar.gz"
      sha256 "889f794312774cc87ed5b63fab98ff38117c304dfa2611f72f76601b40dc75da"

      def install
        bin.install "tfren"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obay/tfren/releases/download/v1.0.3/tfren_Darwin_arm64.tar.gz"
      sha256 "94aac8a7eeea678538199710091a8816d27d83c1267d38aeb2c0f63fdb750dcf"

      def install
        bin.install "tfren"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/tfren/releases/download/v1.0.3/tfren_Linux_x86_64.tar.gz"
      sha256 "24eeb45aaab33fb2b581922cad04b2615af2a63edce5ba9896a0ac08d462be77"
      def install
        bin.install "tfren"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/tfren/releases/download/v1.0.3/tfren_Linux_arm64.tar.gz"
      sha256 "21de53c0df250fbd57ab7e1bb9b3cac7913607baa8b371da803d390dcdb1cb9d"
      def install
        bin.install "tfren"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfren version")
  end
end
