# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfren < Formula
  desc "Terraform file organizer - splits and renames files according to OTN naming convention."
  homepage "https://github.com/obay/tfren"
  version "1.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obay/tfren/releases/download/v1.0.2/tfren_Darwin_x86_64.tar.gz"
      sha256 "0972d74dcb57696569d2e8bb7f6952711753b3524149dcfa05fc15ac24ab3db8"

      def install
        bin.install "tfren"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obay/tfren/releases/download/v1.0.2/tfren_Darwin_arm64.tar.gz"
      sha256 "6c05e334496567673fbd83833a14566b177aac89e3ed26cbb7d8e2e0fd647178"

      def install
        bin.install "tfren"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/tfren/releases/download/v1.0.2/tfren_Linux_x86_64.tar.gz"
      sha256 "12b861fc26357840d5cff59ec81c72bf17aedd7e1b03bce7af331cea31bbf190"
      def install
        bin.install "tfren"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/tfren/releases/download/v1.0.2/tfren_Linux_arm64.tar.gz"
      sha256 "306d242308dd0815874605ce6b0cdc1bd12eec18bda3665e0cbe2b857c6353c4"
      def install
        bin.install "tfren"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfren version")
  end
end
