# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfren < Formula
  desc "Terraform file organizer - splits and renames files according to OTN naming convention."
  homepage "https://github.com/obay/tfren"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/obay/tfren/releases/download/v1.0.4/tfren_Darwin_x86_64.tar.gz"
      sha256 "7e1b4ee765279ffab48ea2375825cbe9298cbc24e592c12f444209ea981a9d45"

      def install
        bin.install "tfren"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/obay/tfren/releases/download/v1.0.4/tfren_Darwin_arm64.tar.gz"
      sha256 "e928427624aca8669135af8206dbdfaa7ae8ebebc8fbebfa228e2d5532330fae"

      def install
        bin.install "tfren"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/tfren/releases/download/v1.0.4/tfren_Linux_x86_64.tar.gz"
      sha256 "7a234a026b5e5924088bafe275ecbc4b89137e6eb8f0196a86222c7b347602e2"
      def install
        bin.install "tfren"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/obay/tfren/releases/download/v1.0.4/tfren_Linux_arm64.tar.gz"
      sha256 "feba64250f1a11f1a82f313bb5ea342eddb814db6c67a0ec79fef28829c3c65c"
      def install
        bin.install "tfren"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfren version")
  end
end
